apiVersion: v1
kind: Pod
metadata:
  name: irsa-test
spec:
  serviceAccountName: orders-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      args: ["s3", "ls", "s3://project3-irsa-demo-342677169816/"]
  restartPolicy: Never
