apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project3-eks
  region: ap-south-2
  version: "1.31"

nodeGroups:
  - name: standard-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
